import PDFDocument from 'pdfkit'

function formatDate(iso) {
  if (!iso) return '—'
  return new Date(iso).toLocaleString('en-PK', {
    dateStyle: 'medium',
    timeStyle: 'short',
  })
}

export function buildPrescriptionPdf(prescription) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 })
    const chunks = []

    doc.on('data', (chunk) => chunks.push(chunk))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)

    const patient = prescription.patient || {}
    const doctor = prescription.doctor || {}
    const profile = prescription.doctor_profile || {}

    doc
      .fontSize(22)
      .fillColor('#0d9488')
      .text('Doctor Hub', { align: 'center' })
    doc
      .fontSize(14)
      .fillColor('#111')
      .text('Electronic Prescription', { align: 'center' })
    doc.moveDown(0.5)
    doc.fontSize(9).fillColor('#666').text(`Rx ID: ${prescription.id}`, { align: 'center' })
    doc.text(`Issued: ${formatDate(prescription.created_at)}`, { align: 'center' })
    doc.moveDown(1)

    doc.fontSize(11).fillColor('#111')
    doc.text('Doctor', { underline: true })
    doc.fontSize(10).text(`${doctor.name || '—'}`)
    if (profile.speciality) doc.text(`Speciality: ${profile.speciality}`)
    if (profile.degree) doc.text(`Qualification: ${profile.degree}`)
    if (profile.treatment) doc.text(`Treatment: ${profile.treatment}`)
    doc.moveDown(0.8)

    doc.fontSize(11).text('Patient', { underline: true })
    doc.fontSize(10).text(`${patient.name || '—'}`)
    if (patient.phone) doc.text(`Phone: ${patient.phone}`)
    if (patient.dob) doc.text(`DOB: ${patient.dob}`)
    doc.moveDown(1)

    doc.fontSize(12).fillColor('#0d9488').text('Medicines prescribed')
    doc.moveDown(0.3)
    doc.fillColor('#111').fontSize(10)

    const medicines = prescription.medicines || []
    if (medicines.length === 0) {
      doc.text('No medicines listed.')
    } else {
      medicines.forEach((med, index) => {
        doc.fontSize(11).text(`${index + 1}. ${med.name || 'Medicine'}`)
        doc.fontSize(10)
        const lines = [
          med.dose && `Dose: ${med.dose}`,
          med.frequency && `Frequency: ${med.frequency}`,
          med.duration && `Duration: ${med.duration}`,
          med.instructions && `Instructions: ${med.instructions}`,
        ].filter(Boolean)
        lines.forEach((line) => doc.text(`   ${line}`))
        doc.moveDown(0.4)
      })
    }

    if (prescription.notes) {
      doc.moveDown(0.5)
      doc.fontSize(11).text('Additional notes')
      doc.fontSize(10).text(prescription.notes)
    }

    doc.moveDown(1.5)
    doc
      .fontSize(8)
      .fillColor('#666')
      .text(
        'This e-prescription was generated by Doctor Hub. It is an immutable medical record and cannot be altered after issue. ' +
          'Not valid without a confirmed doctor–patient relationship. Seek in-person care for emergencies.',
        { align: 'justify' }
      )

    doc
      .fontSize(8)
      .text(
        `Generated ${formatDate(new Date().toISOString())} — Doctor Hub © ${new Date().getFullYear()}`,
        50,
        doc.page.height - 50,
        { align: 'center', width: doc.page.width - 100 }
      )

    doc.end()
  })
}
